// verilog wrapper for fpga64_sid_iec vhdl entity (ties off unused ports)
module c64_core_wrapper (
    input  logic        clk32,
    input  logic        reset_n,
    input  logic [1:0]  bios,
    input  logic        ntscMode,
    input  logic [1:0]  vic_variant,
    input  logic [2:0]  palette,
    input  logic [7:0]  ext_kbd_pai,
    output logic [7:0]  ext_kbd_pao,
    input  logic [7:0]  ext_kbd_pbi,
    output logic [7:0]  ext_kbd_pbo,
    input  logic [6:0]  joyA,
    input  logic [6:0]  joyB,
    output logic [15:0] ramAddr,
    input  logic [7:0]  ramDin,
    output logic [7:0]  ramDout,
    output logic        ramCE,
    output logic        ramWE,
    output logic        hsync,
    output logic        vsync,
    output logic [7:0]  r,
    output logic [7:0]  g,
    output logic [7:0]  b
);
    logic [17:0] audio_l, audio_r;
    logic        nmi_ack, io_cycle, ext_cycle, refresh;
    logic        romL, romH, UMAXromH, IOE, IOF;
    logic        freeze_key, mod_key, tape_play, dma_cycle;
    logic [7:0]  dma_din;
    logic        iec_data_o, iec_clk_o, iec_atn_o;
    logic [7:0]  pb_o;
    logic        pa2_o, pc2_n_o, sp2_o, sp1_o, cnt2_o, cnt1_o;
    logic        cass_motor, cass_write;

    fpga64_sid_iec u_fpga64 (
        .clk32(clk32),
        .reset_n(reset_n),
        .bios(bios),
        .pause(1'b0),
        .ext_kbd_pai(ext_kbd_pai),
        .ext_kbd_pao(ext_kbd_pao),
        .ext_kbd_pbi(ext_kbd_pbi),
        .ext_kbd_pbo(ext_kbd_pbo),
        .ramAddr(ramAddr),
        .ramDin(ramDin),
        .ramDout(ramDout),
        .ramCE(ramCE),
        .ramWE(ramWE),
        .io_cycle(io_cycle),
        .ext_cycle(ext_cycle),
        .refresh(refresh),
        .cia_mode(1'b0),
        .turbo_mode(2'b00),
        .turbo_speed(2'b00),
        .vic_variant(vic_variant),
        .ntscMode(ntscMode),
        .hsync(hsync),
        .vsync(vsync),
        .palette(palette),
        .r(r),
        .g(g),
        .b(b),
        .game(1'b1),
        .exrom(1'b1),
        .io_rom(1'b0),
        .io_ext(1'b0),
        .io_data(8'hFF),
        .irq_n(1'b1),
        .nmi_n(1'b1),
        .nmi_ack(nmi_ack),
        .romL(romL),
        .romH(romH),
        .UMAXromH(UMAXromH),
        .IOE(IOE),
        .IOF(IOF),
        .freeze_key(freeze_key),
        .mod_key(mod_key),
        .tape_play(tape_play),
        .dma_req(1'b0),
        .dma_cycle(dma_cycle),
        .dma_din(dma_din),
        .irq_ext_n(1'b1),
        .joyA(joyA),
        .joyB(joyB),
        .pot1(8'hFF),
        .pot2(8'hFF),
        .pot3(8'hFF),
        .pot4(8'hFF),
        .audio_l(audio_l),
        .audio_r(audio_r),
        .sid_filter(2'b11),
        .sid_ver(2'b00),
        .sid_mode(3'b000),
        .sid_cfg(4'b0000),
        .sid_fc_off_l(13'd0),
        .sid_fc_off_r(13'd0),
        .sid_ld_clk(1'b0),
        .sid_ld_addr(12'd0),
        .sid_ld_data(16'd0),
        .sid_ld_wr(1'b0),
        .sid_digifix(1'b0),
        .pb_i(8'hFF),
        .pb_o(pb_o),
        .pa2_i(1'b1),
        .pa2_o(pa2_o),
        .pc2_n_o(pc2_n_o),
        .flag2_n_i(1'b1),
        .sp2_i(1'b1),
        .sp2_o(sp2_o),
        .sp1_i(1'b1),
        .sp1_o(sp1_o),
        .cnt2_i(1'b1),
        .cnt2_o(cnt2_o),
        .cnt1_i(1'b1),
        .cnt1_o(cnt1_o),
        .iec_data_o(iec_data_o),
        .iec_data_i(1'b1),
        .iec_clk_o(iec_clk_o),
        .iec_clk_i(1'b1),
        .iec_atn_o(iec_atn_o),
        .c64rom_addr(14'd0),
        .c64rom_data(8'd0),
        .c64rom_wr(1'b0),
        .cass_motor(cass_motor),
        .cass_write(cass_write),
        .cass_sense(1'b1),
        .cass_read(1'b1)
    );
endmodule
